import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const armelie = localFont({
  src: "../public/fonts/Armelie-Regular.otf",
  variable: "--font-armelie",
});

const hunders = localFont({
  src: "../public/fonts/Hunders.ttf",
  variable: "--font-hunders",
});

export const metadata: Metadata = {
  title: "Sumanjeet Prasad - Creative Director",
  description: "Generated by create next app",
};

import SmoothScroll from "./components/SmoothScroll";
import CustomCursor from "./components/CustomCursor";
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        armelie.variable,
        hunders.variable,
        "font-sans",
        inter.variable
      )}
    >
      <body className="min-h-full flex flex-col bg-black">
        <CustomCursor />
        <Analytics />
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  );
}
